import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Container, Flex } from '@chakra-ui/react'
import SearchProvince from '../components/SearchProvince'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex h="90vh" justify="center" align="center">
        <SearchProvince />
      </Flex>
    </Container>
  )
}
